- name: Install apt packages
  apt:
    name: "{{ apt_pkg }}"
    state: latest
  loop:
    - postgresql-client-common
    - postgresql-client-12
    - libxml2-utils
    - unattended-upgrades
    - openresolv
    - wireguard
    - unzip
  loop_control:
    loop_var: apt_pkg
  become: yes
